from textwrap import dedent

from cax import parser


def test_parse_new_cactus_prepare_format():
    text = dedent(
        """\
        cactus-prepare examples/evolverMammals.txt --outDir steps-output --outSeqFile steps-output/evovlerMammals.txt --outHal steps-output/evolverMammals.hal --jobStore jobstore
        ## generated by : /mnt/sda/tianqinzhong/miniconda3/envs/cactus/bin/cactus-prepare examples/evolverMammals.txt --outDir steps-output --outSeqFile steps-output/evovlerMammals.txt --outHal steps-output/evolverMammals.hal --jobStore jobstore
        ## date : 2026-01-26 16:58:53.529717
        ## cactus commit : 4e34e49785b99ac9d39b06c87356580749e0df4d

        ## Preprocessor
        cactus-preprocess jobstore/0 examples/evolverMammals.txt steps-output/evovlerMammals.txt --inputNames simHuman_chr6 simCow_chr6 simDog_chr6 simMouse_chr6 simRat_chr6   --logFile steps-output/logs/preprocess-simHuman_chr6.log

        ## Alignment
        ### Round 0
        cactus-blast jobstore/1 steps-output/evovlerMammals.txt steps-output/Anc2.paf --root Anc2   --logFile steps-output/logs/blast-Anc2.log
        cactus-align jobstore/2 steps-output/evovlerMammals.txt steps-output/Anc2.paf steps-output/Anc2.hal --root Anc2   --logFile steps-output/logs/align-Anc2.log
        cactus-hal2fasta jobstore/3 steps-output/Anc2.hal Anc2 steps-output/Anc2.fa.gz   --logFile steps-output/logs/hal2fasta-Anc2.log

        cactus-blast jobstore/4 steps-output/evovlerMammals.txt steps-output/mr.paf --root mr   --logFile steps-output/logs/blast-mr.log
        cactus-align jobstore/5 steps-output/evovlerMammals.txt steps-output/mr.paf steps-output/mr.hal --root mr   --logFile steps-output/logs/align-mr.log
        cactus-hal2fasta jobstore/6 steps-output/mr.hal mr steps-output/mr.fa.gz   --logFile steps-output/logs/hal2fasta-mr.log

        ### Round 1
        cactus-blast jobstore/7 steps-output/evovlerMammals.txt steps-output/Anc1.paf --root Anc1   --logFile steps-output/logs/blast-Anc1.log
        cactus-align jobstore/8 steps-output/evovlerMammals.txt steps-output/Anc1.paf steps-output/Anc1.hal --root Anc1   --logFile steps-output/logs/align-Anc1.log
        cactus-hal2fasta jobstore/9 steps-output/Anc1.hal Anc1 steps-output/Anc1.fa.gz   --logFile steps-output/logs/hal2fasta-Anc1.log

        ### Round 2
        cactus-blast jobstore/10 steps-output/evovlerMammals.txt steps-output/Anc0.paf --root Anc0   --logFile steps-output/logs/blast-Anc0.log
        cactus-align jobstore/11 steps-output/evovlerMammals.txt steps-output/Anc0.paf steps-output/Anc0.hal --root Anc0   --logFile steps-output/logs/align-Anc0.log
        cactus-hal2fasta jobstore/12 steps-output/Anc0.hal Anc0 steps-output/Anc0.fa.gz   --logFile steps-output/logs/hal2fasta-Anc0.log

        ## HAL merging
        cactus-halAppendSubtrees jobstore/13 steps-output/Anc0.hal steps-output/Anc1.hal steps-output/Anc2.hal steps-output/mr.hal steps-output/evolverMammals.hal   --logFile steps-output/logs/halAppend-Anc1.log
        """
    )

    plan = parser.parse_prepare_script(text)

    assert plan.out_seq_file.endswith("evovlerMammals.txt")
    assert len(plan.preprocess) == 1
    assert len(plan.rounds) == 4
    assert len(plan.hal_merges) == 1

    hal2fasta_steps = [
        step
        for round_entry in plan.rounds
        for step in round_entry.hal2fasta_steps
    ]
    assert hal2fasta_steps
    assert all(step.kind == "hal2fasta" for step in hal2fasta_steps)
    assert all(step.out_files for step in hal2fasta_steps)

    halmerge = plan.hal_merges[0]
    assert halmerge.kind == "halmerge"
    assert halmerge.root == "Anc1"
